# Generated by Django 6.0.5 on 2026-05-19 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prompts", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"ordering": ("name",)},
        ),
        migrations.AlterField(
            model_name="author",
            name="display_name",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name="comment",
            unique_together={("user", "prompt")},
        ),
    ]
