# Generated by Django 6.0.5 on 2026-05-19 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("prompts", "0002_alter_category_options_alter_author_display_name_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="comment",
            unique_together=set(),
        ),
    ]
